sds/overcommit

bin/overcommit
lib/overcommit/cli.rb
lib/overcommit/hook/pre_push/base.rb
lib/overcommit/hook_context.rb
lib/overcommit/hook_context/base.rb
lib/overcommit/hook_context/pre_push.rb
spec/overcommit/cli_spec.rb
spec/overcommit/hook_context/base_spec.rb
spec/overcommit/hook_context/commit_msg_spec.rb
spec/overcommit/hook_context/post_checkout_spec.rb
spec/overcommit/hook_context/post_commit_spec.rb
spec/overcommit/hook_context/post_merge_spec.rb
spec/overcommit/hook_context/post_rewrite_spec.rb
spec/overcommit/hook_context/pre_commit_spec.rb
spec/overcommit/hook_context/pre_push_spec.rb
spec/overcommit/hook_context/run_all_spec.rb
spec/overcommit/utils_spec.rb
template-dir/hooks/overcommit-hook
template-dir/hooks/pre-push

[Pre-push](https://github.com/git/git/blob/master/templates/hooks--pre-push.sample) hooks are passed the name and url of the remote as arguments, and STDIN contains info about pushed commits, one per line, in the format `local_ref local_sha1 remote_ref remote_sha1`.

Add support for pre-push hooks

---

config/default.yml
lib/overcommit/hook/commit_msg/spellcheck.rb
spec/overcommit/hook/commit_msg/spellcheck_spec.rb

This hook uses [hunspell](http://hunspell.sourceforge.net/) to check the commit message for potential misspellings, and suggests alternate spellings if available.

Add Spellcheck commit-msg hook

---

config/default.yml
lib/overcommit/hook/pre_rebase/base.rb
lib/overcommit/hook_context/pre_rebase.rb
spec/overcommit/hook_context/pre_rebase_spec.rb
spec/overcommit/utils_spec.rb
template-dir/hooks/pre-rebase

`pre-rebase` hooks can be used to prevent already-pushed commits from being rebased, to check that rebased commits are not present in other branches, etc.

Add support for pre-rebase hooks

---

lib/overcommit/hook/pre_commit/base.rb

This makes it easier for pre-commit hooks to check whether the hook run was triggered by an amendment.

Add #amendment? delegator to Hook::PreCommit::Base

---

CHANGELOG.md
config/default.yml

The image_optim gem can run on SVG files, so we may as well include them
here.

Add **/*.svg to ImageOptim default include configuration

---

lib/overcommit/git_version.rb

This prevents something like `1.9.5.msysgit` from being extracted as `1.9.5.`, which causes `Gem::Version.new` to throw an error.

Don't include trailing period in GIT_VERSION

---

lib/overcommit/git_repo.rb
lib/overcommit/hook/pre_commit/author_name.rb
lib/overcommit/hook_context/pre_commit.rb
lib/overcommit/hook_context/run_all.rb
lib/overcommit/installer.rb
lib/overcommit/logger.rb
spec/integration/committing_spec.rb
spec/integration/disable_overcommit_spec.rb
spec/integration/resolving_cherry_pick_conflict_spec.rb
spec/integration/resolving_merge_conflict_spec.rb
spec/overcommit/git_repo_spec.rb
spec/overcommit/hook/pre_commit/berksfile_check_spec.rb
spec/overcommit/hook/pre_commit/bundle_check_spec.rb
spec/overcommit/hook/pre_commit/json_syntax_spec.rb
spec/overcommit/hook_context/post_commit_spec.rb
spec/overcommit/hook_context/post_merge_spec.rb
spec/overcommit/hook_context/pre_commit_spec.rb
spec/overcommit/hook_context/pre_rebase_spec.rb
spec/overcommit/hook_context/run_all_spec.rb
spec/overcommit/utils_spec.rb
spec/support/shell_helpers.rb

These changes were extracted from #185. They consist mostly of using Ruby `File` and `FileUtils` API methods in place of forked shell processes for things like file IO.
Single-quotes have also been replaced with double-quotes in all shell commands, since single-quotes are not treated as string delimiters on the Windows command line.

Cross-platform compatibility changes

---

lib/overcommit/git_repo.rb

Extracted from #185.
Including the trailing newline results in an error on Windows:
```
fatal: Corrupt MERGE_HEAD file (<commit-hash>)
```

Restore MERGE_HEAD and CHERRY_PICK_HEAD without newline

---

config/default.yml

Older versions of grep ([2.4.2](https://github.com/brigade/overcommit/pull/185#issuecomment-94234017), for example) do not support the `\s` whitespace character class.

Replace '\s' with "[ \t]" for older versions of grep

---

lib/overcommit/hook/commit_msg/base.rb
lib/overcommit/hook/commit_msg/capitalized_subject.rb
lib/overcommit/hook/commit_msg/hard_tabs.rb
lib/overcommit/hook/commit_msg/single_line_subject.rb
lib/overcommit/hook/commit_msg/text_width.rb
lib/overcommit/hook/commit_msg/trailing_period.rb
lib/overcommit/hook_context/commit_msg.rb
spec/overcommit/hook/commit_msg/capitalized_subject_spec.rb
spec/overcommit/hook/commit_msg/hard_tabs_spec.rb
spec/overcommit/hook/commit_msg/single_line_subject_spec.rb
spec/overcommit/hook/commit_msg/text_width_spec.rb
spec/overcommit/hook/commit_msg/trailing_period_spec.rb
spec/overcommit/hook_context/commit_msg_spec.rb

Pass commit-msg hooks when commit message is empty

---

CHANGELOG.md
lib/overcommit/hook/base.rb

Exclude files that don't exist from applicable_files

---

lib/overcommit/hook/pre_commit/semi_standard.rb
lib/overcommit/hook/pre_commit/standard.rb
spec/overcommit/hook/pre_commit/semi_standard_spec.rb
spec/overcommit/hook/pre_commit/standard_spec.rb

* Use stdout instead of stderr
* Update regexp to account for space before file path in output
* Update tests to mimic latest tool output
See brigade/overcommit#231

Fix and update (semi)standard hooks

---

lib/overcommit/hook/base.rb

`PreCommit` and `PostRewrite` hooks may aggregate changes from more than one commit, so `modified_files` is not guaranteed to be sorted already.

Sort `applicable_files` in lexicographical order

---

config/default.yml
lib/overcommit/hook/post_checkout/bower_install.rb
lib/overcommit/hook/post_commit/bower_install.rb
lib/overcommit/hook/post_merge/bower_install.rb
lib/overcommit/hook/post_rewrite/bower_install.rb
lib/overcommit/hook/shared/bower_install.rb
spec/overcommit/hook/post_checkout/bower_install_spec.rb
spec/overcommit/hook/post_commit/bower_install_spec.rb
spec/overcommit/hook/post_merge/bower_install_spec.rb
spec/overcommit/hook/post_rewrite/bower_install_spec.rb

Essentially identical to #251, but for [bower](http://bower.io/).

Add BowerInstall post-{commit,checkout,merge,rewrite} hooks

---

.rubocop.yml

RuboCop has been complaining that the `ParallelAssignment` cop was improperly namespaced.

Fix namespace for ParallelAssignment cop

---

config/default.yml
lib/overcommit/hook/pre_commit/coffee_lint.rb
spec/overcommit/hook/pre_commit/coffee_lint_spec.rb

This allows us to remove the dependency on the 'json' library and
simplify the message parsing logic. It also makes it easier to parse
concatenated results of multiple calls when splitting argument lists.

Use csv formatter for coffeelint

---

config/default.yml
lib/overcommit/hook/pre_commit/hlint.rb
spec/overcommit/hook/pre_commit/hlint_spec.rb

[Hlint](https://github.com/ndmitchell/hlint) is a static analyzer for Haskell.
Closes #260.

Add pre-commit hook for hlint

---

README.md

`svg` provides a higher-quality badge that's visually consistent with the others.

Use svg instead of png for Code Climate badge

---

config/default.yml
lib/overcommit/hook/pre_commit/nginx_test.rb
spec/overcommit/hook/pre_commit/nginx_test_spec.rb

Finally got around to this. The hook uses `nginx -t` on each config file individually and aggregates any errors.
Closes #255

Add NginxTest pre-commit hook to test nginx configs

---

lib/overcommit/git_repo.rb

If the ~/.gitconfig sets the `diff.renames` option to a true value 4 of
the 5 tests run with `rspec -d renam` fail.  Fix this by adding `R` to
the list of change types included in the `--diff-filter` option.  All
tests continue to pass if this option is left at the default value.

Fix tests with git diff.renames option set

---

config/default.yml
lib/overcommit/hook/pre_commit/rails_best_practices.rb
spec/overcommit/hook/pre_commit/rails_best_practices_spec.rb

We were working on one Rails project with @paladiy and found out that `overcommit` had no support of `rails_best_practices` gem, so this is its basic integration.

Add basic support of rails_best_practices in pre-commit hooks

---

spec/integration/run_flag_spec.rb

Should fix the remaining broken test.

Use .bat extension for test hook script on Windows

---

README.md
config/default.yml
lib/overcommit/configuration.rb
lib/overcommit/configuration_validator.rb
lib/overcommit/hook/base.rb
lib/overcommit/hook_runner.rb
lib/overcommit/printer.rb
lib/overcommit/utils.rb
spec/overcommit/configuration_validator_spec.rb

Add support for running hooks in parallel.
This has been on the [todo](https://github.com/brigade/overcommit/issues/144) list for a while, and while I'm not satisfied with this implementation I think it helps push us forward.
I went with bare threads instead of Celluloid because Celluloid supports only Ruby 2.0+ and I think it was pretty heavyweight for what we're trying to do here.
The biggest challenge here is dealing with interrupts, which is why you see `rescue Interrupt` in a number of places. Since signals aren't yet supported for multi-threaded applications (see the documentation for `Thread.handle_interrupt`), we need to handle a lot of this explicitly.
The output has changed slightly: since we don't run hooks serially, we have to wait until they finish before displaying anything …

Run hooks in parallel

---

lib/overcommit/hook/commit_msg/message_format.rb
spec/overcommit/hook/commit_msg/message_format_spec.rb

The `EmptyMessage` hook already covers this case.

Don't fail on empty message in MessageFormat hook

---

lib/overcommit/hook/pre_commit/coffee_lint.rb

Line number should be `Fixnum` so that overcommit can accurately determine if it's modified line or not. Refs #364

Fix CoffeeLint for modified lines

---

CHANGELOG.md
lib/overcommit/hook/pre_commit/scalastyle.rb
spec/overcommit/hook/pre_commit/scalastyle_spec.rb

Scalastyle: capture messages with no line number

---

config/default.yml

The files with `.ru` extension is often used to describe [Rackup config](https://github.com/rack/rack/wiki/(tutorial)-rackup-howto). Usually it's `config.ru`, but could be different. They contain regular ruby code, so they should be also checked by rubocop.

Add *.ru matcher to rubocop hook files list

---

lib/overcommit/hook/commit_msg/text_width.rb
spec/overcommit/hook/commit_msg/text_width_spec.rb

These are special commit message prefixes created by git commands, and
should not count towards the subject line length check.
This fixes #384

Fix TextWidth to allow for fixup!/squash! commits

---

lib/overcommit/installer.rb
spec/integration/installing_overcommit_spec.rb
spec/overcommit/installer_spec.rb
template-dir/hooks/commit-msg
template-dir/hooks/overcommit-hook
template-dir/hooks/post-checkout
template-dir/hooks/post-commit
template-dir/hooks/post-merge
template-dir/hooks/post-rewrite
template-dir/hooks/pre-commit
template-dir/hooks/pre-push
template-dir/hooks/pre-rebase

As explained in #400, creating symlinks on Windows with `mklink` requires admin privileges, which makes Overcommit unusable for non-admin users. Our handling of symlinks on Windows is already brittle enough, so we may as well switch to copying.
We could symlink on *nix and copy on Windows, but that would unnecessarily complicate the code and specs, and I think it's better to keep behavior consistent across platforms anyway.

Copy hook files instead of linking them

---

config/default.yml
lib/overcommit/hook/commit_msg/commitplease.rb

[Commitplease][1] is an npm module that uses commit-msg hook to check that a commit message follows a certain style guide.
I have described how [it works with overcommit][2] and would be grateful if you could sanity-check that :)
Closes #405
Refs jzaefferer/commitplease#72
[1]: https://github.com/jzaefferer/commitplease
[2]: https://github.com/jzaefferer/commitplease/issues/72#issuecomment-235827024

Add commit-msg hook for commitplease

---

config/default.yml
lib/overcommit/hook/pre_commit/fasterer.rb
spec/overcommit/hook/pre_commit/fasterer_spec.rb

This hook is to run [fasterer](https://github.com/DamirSvrtan/fasterer) to suggest some speed improvements which you can check in detail at the [fast-ruby repo](https://github.com/JuanitoFatas/fast-ruby).
I am not good at English, but I will always do my best.
If you have any question or advice, please don't hesitate to tell me. 🍻

Add pre commit hook for fasterer

---

CHANGELOG.md
lib/overcommit/hook/pre_commit/rails_schema_up_to_date.rb
spec/overcommit/hook/pre_commit/rails_schema_up_to_date_spec.rb

A new Rails app has no migration files, but if `db:migrate` has been run, then it will have a `schema.rb` with version 0. This would result in the failure "You're trying to change the schema without adding a migration file", which is a false negative.
Fix this by adding a `non_zero_schema_version?` test such that a schema at version 0 is allowed to be committed without any migrations present.
I've included a test and CHANGELOG entry. Fixes #417

Fix RailsSchemaUpToDate for new Rails projects

---

.travis.yml

Our Travis builds fail for JRuby with a mysterious:
```
Check Travis CI configuration......................[TravisLint] FAILED
Hook raised unexpected error
Cannot run program "travis" (in directory "/home/travis/build/brigade/overcommit"):
error=2, No such file or directory
```
...and similarly for other executables, e.g. `rubocop`.
This appears to be specific to the JRuby runtime. Since we don't care if
Overcommit runs work on JRuby, skip Overcommit for JRuby builds.

Skip Overcommit builds for JRuby

---

.travis.yml
Gemfile
README.md
overcommit.gemspec

No need to drop support for 2.0 altogether, we just need to pin `net-http-persistent` below `3.0`.

Keep net-http-persistent below 3.0 for Ruby 2.0 compatibility

---

CHANGELOG.md
README.md
config/default.yml
lib/overcommit/hook/post_commit/commitplease.rb
spec/overcommit/hook/post_commit/commitplease_spec.rb

`CommitMsg` hook works only on commit messages. Unfortunately
`commitplease` does not allow to pass a message directly on it, it only
works on posted commits. That's why this hooks needs to be moved to
`PostCommit` section - `commitplease` needs to actually see the
commit.

Moved `Commitplease` hook from `CommitMsg` to `PostCommit`

---

README.md
config/default.yml
lib/overcommit/hook/pre_commit/rake_target.rb
lib/overcommit/hook/pre_push/rake_target.rb
lib/overcommit/hook/shared/rake_target.rb
spec/overcommit/hook/pre_commit/rake_target_spec.rb
spec/overcommit/hook/pre_push/rake_target_spec.rb

Allow to run rake targets as pre-commit and pre-push hooks.
The first unsuccessfull exit code of a specified rake task
will fail the hook.
Example configuration: 
```yaml 
PreCommit: 
RakeTask: 
enabled: true 
targets: 
- 'validate' 
- 'lint' 
PrePush: 
RakeTask: 
enabled: true 
targets: 
- 'test' 
```
If considired for merging I would require  a hint howto test for a raised error on missing targets parameter. :-)

Add RakeTarget pre-commit and pre-push hook

---

config/default.yml
lib/overcommit/hook/pre_push/pytest.rb
spec/overcommit/hook/pre_push/pytest_spec.rb

Add hook for [`pytest`](https://github.com/pytest-dev/pytest), a `python` testing framework.
Closes #462.

Add pre-push hook for pytest

---

lib/overcommit/hook_context/pre_commit.rb

Since it's being forwarded to, in Ruby 2.4 it throws a warning.

Make HookContext::PreCommit#initial_commit? public

---

.travis.yml

This is the result of me exploring why the jruby build suddenly started failing. An update to bundler made installing the rainbow gem fail. 
https://github.com/sickill/rainbow/issues/48
I kept all the attempts I made at fixing the issue as separate attempts, to help understand the process better. I'll probably squash before merging though, to keep the git history a little cleaner.

Fix jruby build

---

CHANGELOG.md
README.md
lib/overcommit/installer.rb
spec/integration/configuration_signing_spec.rb
spec/integration/installing_overcommit_spec.rb

Previously, we required users to explicitly run `overcommit --sign` in their repositories after running `overcommit --install`. This was slightly annoying and made for a poor user onboarding experience.
For all practical purposes, the initial bootstrap case seems like one where ease of getting started with the tool trumps the risk of malicious code execution via hooks. It is reasonable to assume that a user who runs `overcommit --install` is accepting responsibility for hook code executed as of that point. It is only on subsequent changes to configuration/hooks that they should be warned to sign the config file/hooks appropriately.

Auto-sign config file when installing hooks the first time

---

lib/overcommit/hook/pre_commit/es_lint.rb
spec/overcommit/hook/pre_commit/es_lint_spec.rb

A user can choose to ignore this behavior by specifying `bindly_pass` option:
```yaml
PreCommit:
EsLint:
enabled: true
on_warn: fail
bindly_pass: true
```

ESLint pre-commit hook fails if there are problems

---

lib/overcommit/hook/pre_push/protected_branches.rb
spec/overcommit/hook/pre_push/protected_branches_spec.rb

This is a fix for Issue #480 
When pushing tags, the pushed ref will look something like this:
```
refs/tags/release-0.1 e0250d9551467b32e2292ff163961b3af0f8ac67 refs/tags/release-0.1 0000000000000000000000000000000000000000
```
This does not match the regular expression pattern of `refs/heads`, hence the failure.

ProtectedBranches should be able to handle pushing tags gracefully

---

README.md
config/default.yml
lib/overcommit/hook/pre_push/git_lfs.rb
spec/overcommit/hook/pre_push/git_lfs_spec.rb

Git LFS installs pre-push hook which:
- checks that git-lfs utility is on PATH, and if no, warns that Git LFS hook should probably be removed
- calls it by executing `git lfs pre-push <remote_name> <remote_url>`
The introduced hook is a Ruby port of the same algorithm
modulo hook disabling note in the warning message.
For the reference, here's the original hook script:
```sh
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```

Add Git LFS pre-push hook

---

config/default.yml

Haml-lint now prints a summary at the end of the run. E.g.
11 files inspected, 1 lint detected
We need to disable that so that overcommit can parse the output
correctly.
Here's some more context: https://github.com/brigade/haml-lint/pull/176
This will help resolve some of the issues seen in #483.

Add `--no-summary` flag to haml-lint

---

CHANGELOG.md
config/default.yml
lib/overcommit/hook/pre_commit/pronto.rb
spec/overcommit/hook/pre_commit/pronto_spec.rb

Add Pronto pre-commit hook

---

config/default.yml

@sds well, this is embarrassing 😄. It took me an hour or two to discover that I've made a bug with my [initial PR](https://github.com/brigade/overcommit/pull/488). I've tested on a branch that had warnings without `--staged` option. As I've started actually using on real commits/branches, I quickly recognised that something is wrong. 😅

Fix Pronto pre-commit hook flags configuration

---

CHANGELOG.md
README.md
config/default.yml
lib/overcommit/hook/pre_commit/license_finder.rb
spec/overcommit/hook/pre_commit/license_finder_spec.rb

Closes #482. 
Sorry this took a while to get around to. This adds a pre-commit hook for the [LicenseFinder](https://github.com/pivotal/LicenseFinder) license checker if any package management related files change.

Add pre-commit hook for LicenseFinder

---

config/default.yml

This partially reverts 3f7c037b after discussion with @sds.

Re-add hard tab exclusions for makefiles and Go

---

lib/overcommit/logger.rb
spec/overcommit/logger_spec.rb

Colorized output is now disabled if the environment variable `OVERCOMMIT_COLOR` is present with the value `0`.
Fixes #508.

Optionally disable colorized output via env

---

lib/overcommit/hook/pre_commit/license_finder.rb

The 'r' at the end of the repository link was missing.

Correct LicenseFinder repository link

---

config/default.yml
lib/overcommit/hook/pre_commit/rst_lint.rb
spec/overcommit/hook/pre_commit/rst_lint_spec.rb

Analyze reStructuredText files with `rst-lint`/`restructuredtext-lint`.

Add rst-lint pre-commit hook

---

config/default.yml
lib/overcommit/hook/pre_commit/mdl.rb

While reviewing the `MESSAGE_REGEX` for `mdl`, I noticed that it is incomplete, and is missing the message output of `mdl`. This updates the regular expression to specifically match this output.

Fix mdl MESSAGE_REGEX

---

lib/overcommit/hook/pre_commit/go_lint.rb

Also tracked at #529.
If I change one file `main.go`, then the `GoLint` hook runs `golint main.go` which is desirable and correct.
However, when I change files that belong to multiple packages such as:
1. `main.go`
2. `lib/util.go`
then the `GoLint` hook runs `golint main.go lib/util.go` which will always return the error (regardless of the presence of any lint errors)
> lib/util.go is in package lib, not main
This is because `golint` can only be used in the following way (from `golint --help`:
> Usage of golint:
> 	golint [flags] # runs on package in current directory
> 	golint [flags] [packages]
> 	golint [flags] [directories] # where a '/...' suffix includes all sub-directories
> 	golint [flags] [files] # all must belong to a single package
This means `golint` shouldn't be passed files …

Run `golint` for each file that has changed

---

lib/overcommit/hook/pre_commit/rails_best_practices.rb
spec/overcommit/hook/pre_commit/rails_best_practices_spec.rb

The `applicable_files` argument wasn't being passed into the `RailsBestPractices` `execute` command during the `run` method. Adding it means that `include`/`exclude` directives in the `.overcommit.yml` function properly.

Pass applicable_files argument to RailsBestPractices Hook

---

CHANGELOG.md
README.md
config/default.yml
lib/overcommit/hook/post_checkout/yarn_install.rb
lib/overcommit/hook/post_commit/yarn_install.rb
lib/overcommit/hook/post_merge/yarn_install.rb
lib/overcommit/hook/post_rewrite/yarn_install.rb
lib/overcommit/hook/shared/yarn_install.rb
spec/overcommit/hook/post_checkout/yarn_install_spec.rb
spec/overcommit/hook/post_commit/yarn_install_spec.rb
spec/overcommit/hook/post_merge/yarn_install_spec.rb
spec/overcommit/hook/post_rewrite/yarn_install_spec.rb

Add yarn install to built-in hooks.

Yarn install

---

lib/overcommit/hook/pre_commit/bundle_audit.rb
spec/overcommit/hook/pre_commit/bundle_audit_spec.rb

Listing ignored files in repositories with a lot of ignored files (such as build artifacts) can take a long time.

Improve performance of Gemfile.lock ignore check for BundleAudit hook

---

lib/overcommit/git_config.rb
spec/overcommit/installer_spec.rb

Joining the repo root doesn't account for `.git` files which have a `gitdir: ...` redirect, but `Overcommit::Utils.git_dir` compensates for that.
```
my-submodule (master) % overcommit --install
Installing hooks into .../my-repo/vendor/my-submodule
.../lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': File exists @ dir_s_mkdir - .../my-repo/vendor/my-submodule/.git (Errno::EEXIST)
from .../lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
from .../lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
from .../lib/ruby/2.4.0/fileutils.rb:206:in `reverse_each'
from .../lib/ruby/2.4.0/fileutils.rb:206:in `block in mkdir_p'
from .../lib/ruby/2.4.0/fileutils.rb:191:in `each'
from .../lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
from .../gems/overcommit-0.41.0/lib/overcommit/installer.rb:80:in …
```

Fix hook install in submodules

---

config/default.yml

Previously the files were only looking for where they live when working
in a Rails app.  Now the file set covers more use cases:
* `settings-production.yml` which is a namespaced settings file
* `settings.yml.erb` which is an ERB pre-processed settings file
* Settings which live in projects like Sinatra and a Rubygem

Add more settings files to ChamberSecurity

---

config/default.yml
lib/overcommit/hook/pre_commit/chamber_compare.rb
spec/overcommit/hook/pre_commit/chamber_compare_spec.rb

One of the pain points that can arise from adding settings to your
application is if you've set a new (required) item in `development` and
`test`, so it works locally and the tests pass, but you've forgotten to
set it in `production`.
Then, you deploy your app only to have it blow up, which sets your
customers out with pitchforks for your head.
Fortunately Chamber provides an easy solution.  Whenever you commit
settings files, Chamber can automatically verify the settings of
multiple different namespace sets to ensure that they're all consistent.
For example, it can take `development`, `test` and `production` and
verify that all the keys that exist in one, exist in the other two.  If
that isn't the case, the hook will fail and the commit will abort.
You can enable it by creating an …

Add ChamberCompare hook

---

config/default.yml
lib/overcommit/hook/post_checkout/composer_install.rb
lib/overcommit/hook/post_commit/composer_install.rb
lib/overcommit/hook/post_merge/composer_install.rb
lib/overcommit/hook/post_rewrite/composer_install.rb
lib/overcommit/hook/shared/composer_install.rb
spec/overcommit/hook/post_checkout/composer_install_spec.rb
spec/overcommit/hook/post_commit/composer_install_spec.rb
spec/overcommit/hook/post_merge/composer_install_spec.rb
spec/overcommit/hook/post_rewrite/composer_install_spec.rb

Run `composer install` hook whenever it detect changes on `composer.json`.

Add ComposerInstall Hook

---

README.md

ComposerInstall was added in d9ac62e7ba9d0b8aa5c66c8998894e8e90f7d87f.

Update README for ComposerInstall Hook

---

config/default.yml
lib/overcommit/hook/pre_commit/chamber_verification.rb
spec/overcommit/hook/pre_commit/chamber_verification_spec.rb

When working with [settings verification](Verifying-Settings), it's
important to remember to let the Approver know that settings have
changed and that the current file signature will no longer match.
You can enable it by creating an `.overcommit.yml` file and adding:
```yaml
ChamberVerification:
enabled: true
```
Whenever you commit any of your settings files, the hook will warn the
user that the signature no longer matches and that the Approver needs to
be notified.
If you'd like to specify the name and email address of the Approver, you
can add that to the configuration:
```yaml
ChamberVerification:
enabled:        true
approver_name:  "Jeff Felchner"
approver_email: "jeff@example.com"
```

Add: ChamberVerification Hook

---

lib/overcommit/hook_context/pre_push.rb
spec/overcommit/hook_context/pre_push_spec.rb
spec/support/git_spec_helpers.rb

Previously, `Overcommit::HookContext::PrePush::modified_files` is set as `[]` which
does not give us any value in `applicable_files` as in `PreCommit` context.
This change updates the method to return list of added and updated files in current branch:
1. compared between current branch and tracking branch if tracking branch is available.
2. compared between current branch with parent branch if tracking branch is not available.
This gives us above values in `applicable_files` in `PrePush` context.
One usage example is we can create a hook to scan prohibited keywords such as `eval`, `console.log`, etc. before pushing to remote. Previously we can only do it in `PreCommit` hook but now we could also do it in `PrePush`.
I think this will also allow us to reuse existing hooks for `PreCommit` in …

Update Pre-Push Context Modified Files

---

lib/overcommit/hook_context/pre_push.rb
spec/overcommit/hook_context/pre_push_spec.rb

Continuation from #536 where it added `modified_files` for `PrePush` context.
This is to add `modified_lines_in_file` for `PrePush` context.

Modified Lines in File for PrePush Context

---

lib/overcommit/hook_context/pre_push.rb
spec/overcommit/hook_context/pre_push_spec.rb

In `pre-push` hook, it receives multiple ref ranges when we pushed multiple branches to remote.
Below is pushing multiple branches plus setting up the upstream branch on remote.
```
command:
git push origin -u tj-test tj-test-2
stdin:
refs/heads/tj-test 62738e20036f58060a8f94ff8cd73733acb6561b refs/heads/tj-test 0000000000000000000000000000000000000000
refs/heads/tj-test-2 feb40b515f598723fe043b7cb9510f28c287d642 refs/heads/tj-test-2 0000000000000000000000000000000000000000
```
Below is pushing multiple branches which already has upstream branch on remote.
```
command:
git push origin tj-test tj-test-2
stdin:
refs/heads/tj-test 61bc13ab2e717633441855d534904c5036f342dd refs/heads/tj-test 62738e20036f58060a8f94ff8cd73733acb6561b
refs/heads/tj-test-2 1e371d2c345e00c34410372dad2d7602aca99908 …
```

Update PrePush Modified Files and Lines with Multiple Branches Push

---

CHANGELOG.md
README.md
config/default.yml
lib/overcommit/hook/pre_commit/yarn_check.rb
spec/overcommit/hook/pre_commit/yarn_check_spec.rb

For users of the [Yarn package manager](https://yarnpkg.com/).
Add a hook that checks that a [`yarn.lock`](https://yarnpkg.com) matches the given `package.json`. This is very similar, and mostly copied from, the existing [`BundleCheck` pre-commit hook](https://github.com/brigade/overcommit/blob/2594697c704930e1a3cf9663b67a235900b5fab1/lib/overcommit/hook/pre_commit/bundle_check.rb).
The primary difference is that `yarn check`'s output needs a bit more massaging. Since it reports a number of issues that are unrelated, or outside the developer's control, check for certain error statements that do indicate the lockfile is out of date.

Add YarnCheck pre-commit hook

---

config/default.yml
lib/overcommit/hook/pre_push/php_unit.rb
spec/overcommit/hook/pre_push/php_unit_spec.rb

Add `PhpUnit` test runner hook for `PrePush` context.

Add PhpUnit Hook for PrePush

---

lib/overcommit/hook/pre_commit/base.rb
lib/overcommit/utils/messages_utils.rb

Extracted messages methods in PreCommit context to Utils module.
This is a step closer to make these PreCommit hooks usable on other context.

Extract Out PreCommit Message Methods to Utils

---

.travis.yml

Bug #554 was specific to Ruby 2.5.0, which is a good reminder that 2.5.0 should be included in the Travis matrix.

Add Ruby 2.5.0 to build matrix

---

README.md
lib/overcommit/git_config.rb
lib/overcommit/utils.rb
spec/overcommit/utils_spec.rb
spec/support/git_spec_helpers.rb

Main reason we didn't previously support work trees was because we had assumed that the `.git` directory was always located in the repository root. With separate work trees, this is not necessarily the case.
Add support by using Git commands to fetch the location of the `GIT_DIR` instead of trying to determine it ourself.

Add support for git-worktree

---

config/default.yml
lib/overcommit/hook/pre_push/cargo_test.rb
spec/overcommit/hook/pre_push/cargo_test_spec.rb

Adds support for running tests with Rust's [Cargo](https://github.com/rust-lang/cargo).

Add support for cargo test

---

config/default.yml
lib/overcommit/hook/pre_commit/php_cs_fixer.rb
spec/overcommit/hook/pre_commit/phpcs_fixer_spec.rb

I tried to implement a php-cs-fixer pre-commit hook.
But somehow it seems that the command is not executed. I opened an issue there: https://github.com/brigade/overcommit/issues/579

PhpCsFixer Pre-Commit hook

---

config/default.yml

Removes flags from TsLint default config, which appeared to break linting. 
The "prose" option for `-t` is also default, so shouldn't be necessary to specify as a flag?
I'm running with `tslint` 5.11.0.
Without the default flags:
```
Running pre-commit hooks
Check for trailing whitespace....................[TrailingWhitespace] OK
Check for local paths in Gemfile................[LocalPathsInGemfile] OK
Check for "token" strings.....................................[FixMe] OK
Check if database schema is up to date..........[RailsSchemaUpToDate] OK
Check YAML syntax........................................[YamlSyntax] OK
Analyze with TSLint..........................................[TsLint] OK
Check Gemfile dependencies..............................[BundleCheck] OK
Analyze with …
```

Fix TsLint defaults

---

config/default.yml
lib/overcommit/hook/prepare_commit_msg/base.rb
lib/overcommit/hook/prepare_commit_msg/replace_branch.rb
lib/overcommit/hook_context/prepare_commit_msg.rb
spec/overcommit/hook/prepare_commit_msg/base_spec.rb
spec/overcommit/hook/prepare_commit_msg/replace_branch_spec.rb
spec/overcommit/hook_context/prepare_commit_msg_spec.rb
spec/overcommit/utils_spec.rb
template-dir/hooks/prepare-commit-msg

As mentioned in [#516](https://github.com/brigade/overcommit/pull/516#issuecomment-338525028), this commit implements the `prepare-commit-msg` hook, with a default hook that prepends a message based on the branch name through regex substitution.

prepare-commit-message hook

---

lib/overcommit/hook/pre_commit/ts_lint.rb
spec/overcommit/hook/pre_commit/ts_lint_spec.rb

Fixes a bug with the newer TsLint version (eg. 5.10.0) where a severity is added to the output:
> src/file/anotherfile.ts[298, 1]: exceeds maximum line length of 140
becomes 
> ERROR: src/file/anotherfile.ts[298, 1]: exceeds maximum line length of 140
Adapted the regexp to be able to extract from both versions. Also extracts the severity of the TsLint output, eg. `:warning` or `:error`.
Related to: https://github.com/brigade/overcommit/pull/595

Add support for new TsLint output format

---

lib/overcommit/hook/pre_commit/bundle_check.rb

TL;DR Add more information on BundleCheck hook error => (...)`or add the Gemfile and/or Gemfile.lock`
Hey guys, 
I was going to add this hook for my work team and I found there I can improve the message of error.
`Run 'bundle check'` it's good, BUT, I already have the problem of a team member that forgot to include the `Gemfile.lock` (What makes the `bundle check` return a happy ok message).
So, I added this piece of information to remember people to commit both Gemfile files :)

Add more information to the BundleCheck error msg

---

lib/overcommit/configuration.rb
lib/overcommit/configuration_loader.rb
lib/overcommit/configuration_validator.rb
lib/overcommit/hook/base.rb
lib/overcommit/hook/pre_commit/chamber_verification.rb
lib/overcommit/logger.rb
lib/overcommit/utils.rb
spec/support/shell_helpers.rb

According to `fasterer`, "Hash#fetch with second argument is slower than Hash#fetch with block"
This provides a very small improvement but since this gem is used with various workflows I feel that any speed improvement is a win.
Before
```
Finished in 1 minute 12.6 seconds (files took 0.49573 seconds to load)
1343 examples, 0 failures
```
After
```
Finished in 1 minute 12.47 seconds (files took 0.48929 seconds to load)
1343 examples, 0 failures
```

Use Hash#fetch with block

---

config/default.yml

Similar to the flag provided by Rubocop, the `--force-exclusion` flag ensures files excluded via the `exclude_paths` config option are still excluded when they are explicitly passed to the `reek` command.

Add --force-exclusion flag to default Reek config

---

.travis.yml
appveyor.yml

This PR extends the matrix.
It also tries to keep the Bundler version before 2.0.

CI: Include Ruby 2.6.0 in build matrix

---

config/default.yml
lib/overcommit/hook/pre_commit/terraform_format.rb
spec/overcommit/hook/pre_commit/terraform_format_spec.rb

Simply check `terraform fmt` to ensure Terraform code is ok.
Fixes #567

Terraform support

---

.travis.yml

This PR simplifies the CI configuration by dropping a now-unused option.

CI: Drop unused Travis option "sudo: false"

---

.git-hooks/pre_commit/master_hooks_match.rb
.rubocop.yml
.travis.yml
CHANGELOG.md
README.md
lib/overcommit/constants.rb
lib/overcommit/hook/pre_commit/berksfile_check.rb
lib/overcommit/hook/pre_commit/bundle_audit.rb
lib/overcommit/hook/pre_commit/bundle_check.rb
lib/overcommit/hook/pre_commit/bundle_outdated.rb
lib/overcommit/hook/pre_commit/yarn_check.rb
lib/overcommit/hook_context/prepare_commit_msg.rb
lib/overcommit/message_processor.rb
lib/overcommit/utils.rb
lib/overcommit/version.rb
overcommit.gemspec

Ruby 2.2 has been EOL since June 2018. Supporting it requires additional effort in our test environment, so drop support.

Drop support for Ruby 2.2

---

lib/overcommit/hook/commit_msg/message_format.rb
spec/overcommit/hook/commit_msg/message_format_spec.rb

Add m flag to regexp check to allow matching over multiple lines.

CommitMsg MessageFormat: multiline match

---

lib/overcommit/hook/post_checkout/bower_install.rb
lib/overcommit/hook/post_checkout/bundle_install.rb
lib/overcommit/hook/post_checkout/composer_install.rb
lib/overcommit/hook/post_checkout/index_tags.rb
lib/overcommit/hook/post_checkout/npm_install.rb
lib/overcommit/hook/post_checkout/yarn_install.rb
lib/overcommit/hook/post_commit/bower_install.rb
lib/overcommit/hook/post_commit/bundle_install.rb
lib/overcommit/hook/post_commit/composer_install.rb
lib/overcommit/hook/post_commit/index_tags.rb
lib/overcommit/hook/post_commit/npm_install.rb
lib/overcommit/hook/post_commit/yarn_install.rb
lib/overcommit/hook/post_merge/bower_install.rb
lib/overcommit/hook/post_merge/bundle_install.rb
lib/overcommit/hook/post_merge/composer_install.rb
lib/overcommit/hook/post_merge/index_tags.rb
lib/overcommit/hook/post_merge/npm_install.rb
lib/overcommit/hook/post_merge/yarn_install.rb
lib/overcommit/hook/post_rewrite/bower_install.rb
lib/overcommit/hook/post_rewrite/bundle_install.rb
lib/overcommit/hook/post_rewrite/composer_install.rb
lib/overcommit/hook/post_rewrite/index_tags.rb
lib/overcommit/hook/post_rewrite/npm_install.rb
lib/overcommit/hook/post_rewrite/yarn_install.rb
lib/overcommit/hook/pre_commit/rake_target.rb
lib/overcommit/hook/pre_push/rake_target.rb

This PR updates the YARD doc comment to avoid warnings:
<details>
```
lib/overcommit/hook/pre_push/rake_target.rb:8: [RedundantBraces] @see tag should not be wrapped in {} (causes rendering issues)
lib/overcommit/hook/post_merge/index_tags.rb:8: [RedundantBraces] @see tag should not be wrapped in {} (causes rendering issues)
lib/overcommit/hook/post_commit/index_tags.rb:8: [RedundantBraces] @see tag should not be wrapped in {} (causes rendering issues)
lib/overcommit/hook/post_merge/npm_install.rb:9: [RedundantBraces] @see tag should not be wrapped in {} (causes rendering issues)
lib/overcommit/hook/pre_commit/rake_target.rb:8: [RedundantBraces] @see tag should not be wrapped in {} (causes rendering issues)
lib/overcommit/hook/post_commit/npm_install.rb:9: [RedundantBraces] @see tag …
```

Avoid YARD warning "RedundantBraces

---

CHANGELOG.md
README.md
config/default.yml
lib/overcommit/hook/pre_commit/file_size.rb
spec/overcommit/hook/pre_commit/file_size_spec.rb

Coming from https://github.com/brigade/overcommit/issues/348
After a few modifications from what I posted in the issue, the result is now this:
Note the file limit is now dynamically output in the hook's description so that it does not need to be repeated in each FileSize error.
Feel free to check the commit history to have an idea of my thinking process.
Improvements such as supporting file size units are welcome, but please let me suggest to open another PRs once this one is merged. 🙇

Implement FileSize pre-commit hook

---

lib/overcommit/hook/pre_commit/stylelint.rb
spec/overcommit/hook/pre_commit/stylelint_spec.rb

The MESSAGE_REGEX for stylelint does not appropriately extract
line numbers >= 10.  This can cause the hook to incorrectly report
errors on modified lines as being for lines that are not modified.
This commit changes the regex to correctly handle multiple digits in
line numbers.
1. Create an empty git repository
2. Install overcommit with the following configuration in `.overcommit.yml` in the repository
```
PreCommit:
Stylelint:
enabled: true
command: "stylelint"
problem_on_unmodified_line: "warn"
```
3. Install `stylelint` and create a `.stylelintrc.json` file in the repository:
```
{
"rules": {
"declaration-block-trailing-semicolon": "always"
}
}
```
4. Create a file named `failing_file.scss` in the repository with the following content:
```
.selector-1 { width: 20%; }
.selector-2 { …
```

Correct extract line number output in Stylelint hook

---

lib/overcommit/git_repo.rb

Shellwords is specific to the Bourne shell. Adjust the implementation to work on Windows.

Fix GitRepo.list_files on Windows platforms

---

config/default.yml
lib/overcommit/hook/prepare_commit_msg/replace_branch.rb
spec/overcommit/hook/prepare_commit_msg/replace_branch_spec.rb

Currently, [ReplaceBranch][1] only runs if the commit type is [commit][2],
which means the hook won't run if you are using a template, for
instance.
This commit enhances the replace_branch prepare commit message hook to
allow specifying the types of commits to not apply this hook to.
So now, I can run this hook during merges, and when using templates by excluding `template` and `merge` in the config
```
ReplaceBranch:
enabled: true
skipped_commit_types: ['message', 'squash']
```
[1]: https://github.com/sds/overcommit/blob/569dc24a64e4b839b247658a688deccb03b716b8/lib/overcommit/hook/prepare_commit_msg/replace_branch.rb#L7
[2]: https://github.com/sds/overcommit/blob/569dc24a64e4b839b247658a688deccb03b716b8/lib/overcommit/hook/prepare_commit_msg/replace_branch.rb#L10

Add more replace_branch config options

---

README.md
config/default.yml
lib/overcommit/hook/pre_commit/ruby_syntax.rb
spec/overcommit/hook/pre_commit/ruby_syntax_spec.rb

Pre-commit hook RubySyntax check ruby files for syntax errors and show where the errors are.
It uses ruby -c to check syntax.
Useful if some files are not loaded automatically when performing the tests.

[FEATURE] New pre-commit hook: RubySyntax

---

Gemfile
README.md
overcommit.gemspec
spec/integration/gemfile_option_spec.rb

ChildProcess no longer includes `ffi` by default (see https://github.com/enkessler/childprocess/issues/150 for context). Ensure we include the gem on Windows builds and update the documentation appropriately.
Based on #649

Relax childprocess dependency version

---

config/default.yml

It looks like this incorrect field name has existed since the inception
of the Stylelint plugin in
https://github.com/sds/overcommit/commit/22229c95854cdd02d19e6e24e20d7df9ac23fea3.

Fix typo: `require_executable` -> `required_executable`

---

config/default.yml
lib/overcommit/hook/pre_commit/ginkgo_focus.rb

This hook warns about focused ginkgo tests left in the code

Add check for Ginkgo Focused tests

---

README.md

The Limitations section was removed here https://github.com/sds/overcommit/commit/10c208081c9f5ff6adf479e7cbce44ad130cb514#diff-04c6e90faac2675aa89e2176d2eec7d8

Get rid of the redundant Limitations item in TOC

---

lib/overcommit/hook_context/pre_commit.rb

We need this in order to work around the behavior of emacs/magit where
it sets GIT_LITERAL_PATHSPECS=1, causing errors like:
Unable to setup environment for pre-commit hook run:
STDOUT:
STDERR:error: pathspec ':/' did not match any file(s) known to git
Overriding the environment variable solves this issue.
Fixes #671.

Disable literal pathspecs when applying stash

---

.travis.yml

This helps not to perform commit like this:
https://github.com/sds/overcommit/commit/2ccd9bd7d86e369135c698ad9c8f9274d8b1570b
or
https://github.com/sds/overcommit/commit/ef8eb44153ac54ac3a3cebaad4fc09e5a78cf9fa

Do not specify minor ruby version for rvm in travis

---

lib/overcommit/hook_context/pre_commit.rb
spec/overcommit/hook_context/pre_commit_spec.rb

It was suggested in #135 that a potential way to avoid unnecessary file change detection and general stashing woes would be to stash changes only when there were unstaged changes that needed to be excluded from the run.
This presents a nice optimization that I wish we had considered long ago. We can simplify the logic now that we see the purpose of this feature a little more clearly: stash only when you need to.
Issue #669 raised an interesting point about the difficulty to detect if a stash entry was created, so we modified the tests to check if a method call was made to validate the logic. This isn't great as it's peeking deep into the implementation, so we added some additional tests that ensured the methods in question actually existed. Not perfect, but gives us some confidence in the …

Avoid stashing changes when all changes are staged

---

appveyor.yml

We get a lot of these warnings in our Windows tests.
warning: CRLF will be replaced by LF in <file name>.
The file will have its original line endings in your working directory.
Remove by adding this setting.

Remove CRLF warnings from AppVeyor builds

---

lib/overcommit/hook_context/commit_msg.rb
spec/overcommit/hook_context/commit_msg_spec.rb

Extend the technique introduced in #519 to instead provide clear instructions on how to re-attempt your commit message starting from the one you previously had.
This is instructional to users who aren't familiar with this feature of Git.
Now commit-msg failures will be followed up with:
Try again with your existing commit message by running:
git commit --edit --file=.git/COMMIT_EDITMSG
The reason we don't attempt to simply re-open the editor is that by the time we've failed the hook, Git has already decided the run has failed and there is no means of recovery.
Closes #651.

Provide better instructions on commit-msg failure

---

lib/overcommit/hook/base.rb
lib/overcommit/hook/pre_push/base.rb
spec/overcommit/hook/pre_push/base_spec.rb

Context
=
Allow user to skip certain Hooks when pushing changes to certain remote repository.
For example, user could a Hook (i.e. RSpec), when pushing to 'heroku' remote name.
```
PrePush:
RSpec:
exclude_remote_names: ['heroku']
```
This is an attempt to solve issue reported in https://github.com/sds/overcommit/issues/588

Introduce "exclude_remote_names" to Skip Hook During PrePush Based on Remote Name

---

lib/overcommit/hook/pre_push/base.rb
lib/overcommit/hook_context/pre_push.rb
spec/overcommit/hook/pre_push/base_spec.rb
spec/overcommit/hook_context/pre_push_spec.rb

Context
=
There are scenario we would like to skip pre-push Hooks when deleting remote branch.
Below is an example of git command to delete remote branch.
```
git push origin :to-be-deleted-branch
```
When we set `ignore_branch_deletions` as true for a PrePush Hook,
it will be skipped during remote branch deletion.

Introduce 'ignore_branch_deletions' Config for PrePush Hooks

---

lib/overcommit/hook/pre_push/protected_branches.rb
spec/integration/protected_branches_spec.rb
spec/overcommit/hook/pre_push/protected_branches_spec.rb

`PrePush::ProtectedBranches` supports a `destructive_only` setting. However, this setting is globally valid for all protected branches. It makes sense to set this setting on a per branch basis. This PR implements the following syntax for the configuration of `ProtectedBranches`.
```yaml
PrePush:
ProtectedBranches:
enabled: true
branches:
- protected
- protected_for_destructive_only:
destructive_only: true
```
In case it is not set on a branch it will fall back to the global setting. Additionally it will use the setting of the first matching branch. 
Example:
```yaml
PrePush:
ProtectedBranches:
enabled: true
branch_patterns:
- releases/*
- releases/v1:
destructive_only: true
```
In this case, a push to `releases/v1` would be forbidden because `releases/*` would match which uses the global …

[PrePush::ProtectedBranches] Implement setting destructive_only per branch

---

.gitignore
README.md
config/default.yml
lib/overcommit/hook/pre_commit/base.rb
lib/overcommit/hook/pre_push/base.rb
lib/overcommit/hook/pre_push/pronto.rb
lib/overcommit/hook/shared/pronto.rb
spec/overcommit/hook/pre_push/pronto_spec.rb

Currently it's possible to add pronto only as PreCommit hook. This PR allows to add pronto as PrePush hook too.

Add pronto to pre_push hooks

---

lib/overcommit/hook/prepare_commit_msg/replace_branch.rb

Removing extra newline in replacement string

---

CHANGELOG.md
config/default.yml
spec/overcommit/hook/pre_commit/yaml_lint_spec.rb

Previously, when yamllint was failing, the exit code of the tool was
reflecting that. However, recently yamllint introduced `--strict`
parameter to do that. Without, it always returns success no matter if
lints were successful or failed. Which caused false-positives in
ovecommit, which was thinking that everything is okay.
This fix adds `--strict` to `yamllint` invocation, to bring back proper
behavior, and force hook to fail, when the tool fails.

Fix `YamlLint` hook.

---

CHANGELOG.md
lib/overcommit/hook/pre_commit/author_name.rb
spec/integration/committing_spec.rb
spec/overcommit/hook/pre_commit/author_name_spec.rb

* Updates the `AuthorName` check to be a little more inclusive by not requiring a first and last name.
* Could also leave this as-is and have a 2-strings type of check (maybe called `AuthorNameTwoStrings`) or something to represent this default setting?  Happy to do that if preferred.

[authorname] allow for non-0

---

config/default.yml
lib/overcommit/hook/prepare_commit_msg/replace_branch.rb
spec/overcommit/hook/prepare_commit_msg/replace_branch_spec.rb

- changes default to not run on `--amend`
- changes the default pattern
- improves the documentation for this hook
- refactors this hook's specs to reduce mocking and increase coverage

Update ReplaceBranch hook to avoid running on `--amend` by default

---

lib/overcommit/hook_context/helpers/stash_unstaged_changes.rb

I'll go with the smallest minimal change. We can always extract this to a module later on.
Closes #728

Make #initial_commit? public

---

lib/overcommit/hook/commit_msg/base.rb

@sds This went under the radar since `modified_files` is delegated via `Overcommit::Hook::Base`.
Now that I tried writing a custom hook I noticed `modified_lines_in_file` is not available inside `Overcommit::Hook::CommitMsg::Base`. I decided to expose only the method I need but I think it's worth thinking about if we want to delegate all methods that come from included modules by default

Delegate `modified_lines_in_file` to context

---

config/default.yml
lib/overcommit/hook/pre_commit/erb_lint.rb
spec/overcommit/hook/pre_commit/erb_lint_spec.rb

[ERB Lint][1] is a linter for Ruby's ERB files. This PR adds a pre commit hook to run this linter. 
I think I covered everything needed to add a new hook, let me know if it needs work!
[1]: https://github.com/Shopify/erb-lint

Add pre commit hook for ERB Lint

---

libexec/index-tags

- use `git rev-parse --git-dir` instead of $GIT_DIR to identify the git directory
- base what files are included in tag generation on the files managed
by git. Exclude files not managed by git

Revise index-tags script

---

lib/overcommit/hook/pre_commit/es_lint.rb
spec/overcommit/hook/pre_commit/es_lint_spec.rb

this is a pr to resolve #743. upon thinking about the cause of this problem more i realized that the output causing the false positive was output emitted by [yarn](https://yarnpkg.org/). my initial thought was to write a regex that would capture output that was yarn specific and ignore it, however this makes several assumptions about how other people may be using overcommit. i think it can be much more simple than that. the regex used to capture eslint messages here:
https://github.com/sds/overcommit/blob/6b25f5d60056614c58c5762a9c6e1fe8919742d2/lib/overcommit/hook/pre_commit/es_lint.rb#L33
actually does a really good job at capturing the data needed for overcommit to output information and adding a small tweak to that rule fixes the issue at hand. eslint messages have no whitespace …

Don't capture false positives

---

lib/overcommit/hook/pre_commit/yaml_lint.rb
spec/overcommit/hook/pre_commit/yaml_lint_spec.rb

Fixes https://github.com/sds/overcommit/issues/737

Fail on yaml lint errors

---

lib/overcommit/hook/pre_commit/yaml_lint.rb

Parse the yamllint output so Overcommit has per-line awareness of
changes to support problem_on_unmodified_line option.

Add parsing of yamllint output

---

lib/overcommit/hook/shared/pronto.rb
spec/overcommit/hook/pre_commit/pronto_spec.rb
spec/overcommit/hook/pre_push/pronto_spec.rb

Pronto might report warnings and that was not being correctly parsed by Overcommit. This is sort of a follow-up from #754.
Before: all warnings and errors were reported as errors. They actually simply crashed at https://github.com/sds/overcommit/blob/7d94fa55a74ceea705645d565a34ecefaca08ea5/lib/overcommit/utils/messages_utils.rb#L23-L30
Now warnings and errors are reported correctly. Examples below:
```
⋊> ~/w/o/cts on rg-test-branch ⨯ be pronto run --exit-code --commit=qa --runner reek
Running Pronto::Reek
app/models/shipment.rb:163 W: Calls 'loc.type' 3 times - [DuplicateMethodCall](https://github.com/troessner/reek/blob/v6.0.4/docs/Duplicate-Method-Call.md)
⋊> ~/w/o/cts on rg-test-branch ⨯ git push --dry-run origin HEAD # using a hook with reek
Running pre-push hooks
Analyzing with …
```

Fix pronto hooks with warning level

---

lib/overcommit/subprocess.rb

Output of commands under windows is not UTF-8 by default, this
can lead to "invalid byte sequence in UTF-8" error on symlink check

Fix encoding of process output under windows

---

lib/overcommit/cli.rb

Sometimes, especially during hook development, you want to force running of a certain type of hook.
This adds an option to the `--run` parameter for specifying a hook type. The default behavior is unchanged.

Support hook type option to `--run`

---

lib/overcommit/hook/pre_commit/stylelint.rb

On the rare occasion messages from Stylelint do not match properly with the existing Regex. This change fixes the issue by matching up until the first colon.
Example:
`/app/assets/stylesheets/_example.scss: line 291, col 1, error - Unexpected duplicate selector ".example:first-child:after", first used at line 282 (no-duplicate-selectors)`
Produces:

Stylelint Pre-Commit: Fixed Message Regex

---

lib/overcommit/logger.rb
lib/overcommit/printer.rb
spec/spec_helper.rb
spec/support/git_spec_helpers.rb

Today a long hook will not print any output until it is complete.
This change introduces flushing (when available) to the status lines so that a hook will output before its run

Partial log flushing to make long hooks intuitive

---

lib/overcommit/subprocess.rb

This appears to break usage under Linux. Until a proper solution can be implemented, revert.
Closes #781.

Revert `Fix encoding of process output under windows`

---

config/default.yml

It seems like this breaks some other workflows. Prefer the user specifying this themselves if they want it.
Closes #782.

Revert addition of `--disable-pending-cops` flag to RuboCop

---

CHANGELOG.md
lib/overcommit/version.rb

* Remove `--disable-pending-cops` as default flag to `RuboCop` pre-commit hook.
* Remove special handling of process output on Windows since it broke on Linux.

Cut version 0.59.1

---

lib/overcommit/hook/prepare_commit_msg/replace_branch.rb
spec/overcommit/hook/prepare_commit_msg/replace_branch_spec.rb

- support trailing spaces in `PrepareCommitMsg::ReplaceBranch`'s `replacement_text` pattern
- When on a branch named `JIRA-123-fix-another-issue`
- And using the below overcommit config
- When I run `git commit -m 'test'` 
- Then I should have commit message `[JIRA-123] test`
- ERROR: I actually get  `[JIRA-123]test`
```
PrepareCommitMsg:
ReplaceBranch:
enabled: true
branch_pattern: '\A([A-Za-z]{1,10}-?[0-9]+).*\z' # JIRA-123-some-branch
replacement_text: '[\1] ' # [JIRA-123] commit message
skipped_commit_types: ['merge', 'squash']
```

support trailing space in replace_branch's 'replacement_text' config

---

config/default.yml
lib/overcommit/hook/pre_commit/mix_format.rb
spec/overcommit/hook/pre_commit/mix_format_spec.rb

Elixir has a built-in formatter that can be run with `mix format` to format the code and `mix format --check-formatted` to list out files which aren't formatted.
This was modeled after the credo hook, but in this case we only get the file list in the output to stderr so that's what we display in the error output.

Add `MixFormat` hook

---

README.md
lib/overcommit/configuration_loader.rb
lib/overcommit/constants.rb
spec/overcommit/configuration_loader_spec.rb

Adds support for an additional configuration file, `.local-overcommit.yml`, in order to allow local configuration on a local computer. That way the main config `.overcommit.yml` can be commited to a repo and a local developer can also add configurations to this new file that do not have to live in the main config.

Add optional additional local configuration

---

lib/overcommit/hook/pre_commit/yaml_syntax.rb

This improves the output for errors safe loading disallowed classes with psych 5.0
It would be nice to offer a way to specify `permitted_classes` somewhere. https://ruby-doc.org/3.2.0/exts/psych/Psych.html

Rescue Psych::DisallowedClass in YamlSyntax

---

lib/overcommit/hook/pre_commit/rails_schema_up_to_date.rb
spec/overcommit/hook/pre_commit/rails_schema_up_to_date_spec.rb

Adds the possibility of adding an encoding config item if you know your `schema.rb` or `structure.sql` file contains non ASCII characters, as in the case of the project I'm working on :grin: 
It's possible you might also want this on migration files, but I haven't included that in this PR, let me know if that's something you'd like to see to get this merged.

Add non ASCII encoding schema support to RailsSchemaUpToDate hook

---

lib/overcommit/configuration_loader.rb
spec/overcommit/configuration_loader_spec.rb

The .local-overcommit.yml did not work as intended. When a repo level .overcommit.yml and .local-overcommit.yml both existed, only the latter applied. Further, the tests only checked that each file was loaded, not that the configs included the expected overrides.
This PR refactors:
- Specs:
- When .overcommit.yml exists, applies settings and has default settings still
- When both .local-overcommit.yml and .overcommit.yml exists has default settings and both files settings applied
- Logic to merge the .overcommit.yml file to default settings and if it exists, .local-overcommit.yml file to both

fix: local overcommit file merges with existing .overcommit.yml file

---

.github/workflows/lint.yml
.github/workflows/tests.yml

This was missed when we switched to using `main`.

Update branch for CI from `master` to `main`

---

.github/workflows/tests.yml
lib/overcommit/hook/pre_commit/rails_schema_up_to_date.rb
lib/overcommit/hook_context/helpers/file_modifications.rb
spec/overcommit/git_repo_spec.rb
spec/overcommit/hook/prepare_commit_msg/base_spec.rb
spec/overcommit/hook_context/commit_msg_spec.rb
spec/overcommit/hook_context/post_checkout_spec.rb
spec/overcommit/hook_context/post_commit_spec.rb
spec/overcommit/hook_context/post_merge_spec.rb
spec/overcommit/hook_context/post_rewrite_spec.rb
spec/overcommit/hook_context/pre_commit_spec.rb
spec/overcommit/hook_context/run_all_spec.rb
spec/overcommit/installer_spec.rb

Am planning on proposing/implementing a new feature, but first I noticed that there are a number of failing specs on main, so I figured I would start with that.
As written, this includes four main adjustments, two of which might actually be bugfixes:
- one spec was hanging indefinitely for me locally on a `Thread.join` call - explicitly capturing the child threads and joining them directly fixed it (might be machine dependent?)
- when an encoding is specified, the rails schema up to date hook was passing arguments incorrectly (kwarg containing `encoding` was being interpreted as the `length` positional arg) (possible bug)
- many specs were attempting to create file submodules without the `protocol.file.allow=always` config option causing failure
- alias detection for amendment appeared to …

Get suite running smoothly again

---

.github/workflows/lint.yml
.github/workflows/tests.yml
Gemfile
lib/overcommit/hook/pre_commit/rails_schema_up_to_date.rb
spec/overcommit/git_repo_spec.rb
spec/overcommit/hook/prepare_commit_msg/base_spec.rb
spec/overcommit/hook_context/commit_msg_spec.rb
spec/overcommit/hook_context/pre_commit_spec.rb
spec/overcommit/installer_spec.rb

Cherry-picked commits from #830, #831, #832, #835, #837 and #839.

Green CI PoC

---

README.md

Clarify Windows support is now best effort, given we don't have tests.

Update README with latest requirements

---

lib/overcommit/hook/pre_commit/stylelint.rb
spec/overcommit/hook/pre_commit/stylelint_spec.rb

Before Stylelint 16, Stylelint emitted its messages on stdout. Hence Overcommit's Stylelint hook was built to read output from stdout.
Starting with Stylelint 16, Stylelint now emits its messages to stderr, which means the existing Overcommit implementation no longer works.
This PR updates Overcommit's Stylelint plugin to check for messages on _both_ stdout and stderr. That way <16 and >=16 versions of Stylelint are supported.
Fixes #823

Support stylelint 16+, which emits messages on stderr

---

overcommit.gemspec

Supported here: https://guides.rubygems.org/specification-reference/#metadata Useful for running https://github.com/MaximeD/gem_updater

Add changelog_uri to gemspec

---

spec/integration/resolving_cherry_pick_conflict_spec.rb
spec/integration/resolving_merge_conflict_spec.rb

The original array was defining the shellwords like this:
`["git", "commit", "-m", "\"Resolve", "conflicts\"", "-i", "some-file"]`
This combined with the most recent git version failed with:
```
error: pathspec 'conflicts"' did not match any file(s) known to git
```
This PR just simplifies the commit message to work with the %w array literal.

Fix spec compatibility with recent git versions

---

lib/overcommit/git_config.rb
spec/overcommit/git_config_spec.rb

While installing overcommit git hooks i noticed that tildes are not expanded to home folders for the `hooksPath` config, the result was a tilde folder in the current directory.
This PR addresses that by switching `File.absolute_path` to `File.expand_path`. The [underlaying implementation](https://github.com/ruby/ruby/blob/v3_3_4/file.c#L3753) in Ruby is exactly the same just with this difference in how `~` is handled.

 Expand tildes(~) for hooksPath

---

lib/overcommit/version.rb
overcommit.gemspec

A `ReDoS vulnerability in REXML` has been identified in versions <3.3.9
Details in GitHub:
- https://github.com/ruby/rexml/security/advisories/GHSA-2rxp-v6pw-ch6m
This is a small bump to the latest patched version. This should resolve anybody getting the following `bundle audit` error when using overcommit:
```
Name: rexml
Version: 3.3.8
CVE: CVE-2024-49761
GHSA: GHSA-2rxp-v6pw-ch6m
Criticality: High
URL: https://github.com/ruby/rexml/security/advisories/GHSA-2rxp-v6pw-ch6m
Title: REXML ReDoS vulnerability
Solution: update to '>= 3.3.9'
```

Bump rexml to >= 3.3.9 to resolve GHSA-2rxp-v6pw-ch6m

---

template-dir/hooks/commit-msg
template-dir/hooks/overcommit-hook
template-dir/hooks/post-checkout
template-dir/hooks/post-commit
template-dir/hooks/post-merge
template-dir/hooks/post-rewrite
template-dir/hooks/pre-commit
template-dir/hooks/pre-push
template-dir/hooks/pre-rebase
template-dir/hooks/prepare-commit-msg

Fixes https://github.com/sds/overcommit/issues/789
`psych` is no longer a default gem, but current and old ruby still ships with it. When we `require 'yaml'`, we activate that gem in whatever version that is bundled with ruby. Later on, we load bundler, and we `Bundler.setup`, which will then activate whatever version specified in the lock file. More often than not, they might not match.
The approach in this PR is to strip the `yaml` dependency completely from the hook scripts, while retaining the ability to configure the Gemfile using it.

Load bundled gems on expected version

---

lib/overcommit/cli.rb
lib/overcommit/hook_context.rb
lib/overcommit/hook_context/base.rb
lib/overcommit/hook_context/diff.rb
spec/integration/diff_flag_spec.rb
spec/overcommit/cli_spec.rb
spec/overcommit/hook_context/diff_spec.rb

For example, running `overcommit --diff main` from a feature branch will run pre-commit hooks against the diff between the two branches.
I was able to very easily leverage existing code for the bulk of the feature - this is mainly just adding the cli option, a hook context to do the execution and some tests based on the existing `--run-all` test.
---
For background, my team is responsible for a couple of really old, really large rails apps. Getting them completely in compliance with our various linters is a huge task that isn't getting done anytime soon (things are funky to the point that we've even observed breakages with "safe" auto-correct functions).
I introduced/started heavily encouraging overcommit so that we at least don't add _new_ linting offenses and things will naturally …

Add `-diff` cli option for running precommit hooks against diffs

---

spec/integration/gemfile_option_spec.rb
template-dir/hooks/commit-msg
template-dir/hooks/overcommit-hook
template-dir/hooks/post-checkout
template-dir/hooks/post-commit
template-dir/hooks/post-merge
template-dir/hooks/post-rewrite
template-dir/hooks/pre-commit
template-dir/hooks/pre-push
template-dir/hooks/pre-rebase
template-dir/hooks/prepare-commit-msg

Setting `gemfile: false` in `.overcommit.yml` is supposed to disable Bundler. However, a recently-introduced bug causes `false` to be interpreted as the name of the gemfile. Bundler looks for a gemfile named "false", which fails, leading overcommit's hooks to crash.
This PR fixes the bug by adjusting the regex used to parse the `gemfile:` line in the config. Now, `false` is no longer interpreted as a gemfile name.
I added an integration test to verify the fix.
Fixes #862

Restore ability to specify "gemfile: false" in config

---

config/default.yml

Related to #863 and [this comment](https://github.com/sds/overcommit/issues/862#issuecomment-2641924147):
> Having a similar problem since we had this line in our `.overcommit.yml`:
> 
> ```yaml
> gemfile: Gemfile # enforce bundled version of overcommit
> ```
>
> And now overcommit doesn't strip out the inline comment, resulting in this weird looking error message:
>
> ```
> Problem loading 'Gemfile # enforce bundled version of overcommit': /path/to/project/Gemfile # enforce bundled version of overcommit not found
> ```
I think adding support for comments in the `gemfile:` regexp is likely overkill and may still not be enough when the next person tries to use yet another YAML feature in that line, but perhaps this little warning would help someone else avoid tripping.

Add note about unsupported YAML features in `gemfile:` line in default.yml

---

.rubocop.yml
Gemfile
lib/overcommit/hook/pre_commit/scalastyle.rb
template-dir/hooks/commit-msg
template-dir/hooks/overcommit-hook
template-dir/hooks/post-checkout
template-dir/hooks/post-commit
template-dir/hooks/post-merge
template-dir/hooks/post-rewrite
template-dir/hooks/pre-commit
template-dir/hooks/pre-push
template-dir/hooks/pre-rebase
template-dir/hooks/prepare-commit-msg

The existing version of RuboCop no longer works against other libraries without deprecation warnings; rather than lock more dependencies, upgrade RuboCop used in project.
```sh
Running pre-commit hooks
Check YAML syntax........................................[YamlSyntax] OK
Check Gemfile dependencies..............................[BundleCheck] OK
Check for trailing whitespace....................[TrailingWhitespace] OK
Analyze with RuboCop........................................[RuboCop] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
`EnsureNode#body` is deprecated and will be changed in the next major version of rubocop-ast. Use `EnsureNode#branch` instead to get the body of the `ensure` branch.
Called from: …
```

Update RuboCop in Gemfile to silence a deprecation warning in build

---

config/default.yml
lib/overcommit/hook/pre_commit/solargraph.rb
spec/overcommit/hook/pre_commit/solargraph_spec.rb

[Solargraph](https://github.com/castwide/solargraph) supports typechecking Ruby files based on YARD tags - combined with overcommit, it can be used in an incremental way on large untyped codebases.

Add solargraph pre-commit hook for typechecking
