sds/overcommit

- README.md
A little animated GIF that demonstrates Overcommit will help people
understand what the project does and should help its adoption.
> Add demo GIF to README.md

- lib/overcommit/git_repo.rb
- spec/overcommit/git_repo_spec.rb
> Quote paths in GitRepo.list_files

- config/default.yml
- lib/overcommit/hook/pre_commit/html_hint.rb
- spec/overcommit/hook/pre_commit/html_hint_spec.rb
[HTMLHint](http://htmlhint.com/) is a linter for HTML.
> Add pre-commit hook for HTMLHint

- lib/overcommit/hook_context/post_checkout.rb
- spec/overcommit/hook_context/post_checkout_spec.rb
Return the set of files added or modified between the previous HEAD and new HEAD.
Refs #245
> Implement HookContext::PostCheckout#modified_files

- CHANGELOG.md
- README.md
- config/default.yml
- lib/overcommit/hook/pre_commit/sqlint.rb
- spec/overcommit/hook/pre_commit/sqlint_spec.rb
[sqlint](https://github.com/purcell/sqlint) is a linter for SQL scripts. We recently accepted a SublimeLinter plugin submission for this tool, and though it's still very young, it seems useful.
\cc @purcell @trezona-lecomte
> Add pre-commit hook for sqlint

- lib/overcommit/hook/pre_commit/sqlint.rb
That's what I get for copy-pasting!
> Fix mistake in Sqlint doc comment

- lib/overcommit/hook/pre_commit/scalastyle.rb
- spec/overcommit/hook/pre_commit/scalastyle_spec.rb
> Teach Scalastyle hook to fail in exceptional conditions

- config/default.yml
- lib/overcommit/hook/pre_commit/dogma.rb
- spec/overcommit/hook/pre_commit/dogma_spec.rb
Dogma is a code style linter for Elixir language.
Dogma's source code is available at https://github.com/lpil/dogma
This pre-commit hook executes dogma and reports errors.
> Add Dogma pre-commit hook to check Elixir source files

- lib/overcommit/hook/pre_commit/es_lint.rb
- default format is changed to stylish
> Add protip about support eslint format

- README.md
Forgot to do this as part of #463.
> Update README.md to mention pytest pre-push hook

- README.md
- config/default.yml
- lib/overcommit/hook/pre_push/python_nose.rb
- spec/overcommit/hook/pre_push/python_nose_spec.rb
Add hook for [`nose`](https://nose.readthedocs.io/en/latest/), another `python` testing framework.
> Add pre-push hook for nose

- README.md
Missed out to add this in 4041485d30a444fffd9fa3194287682f17f95937.
> Add PhpUnit to ReadMe

- README.md
- config/default.yml
- lib/overcommit/hook/pre_commit/swift_lint.rb
- spec/overcommit/hook/pre_commit/swift_lint_spec.rb
- Add SwiftLint to pre-commit hook
- Update README
> SwiftLint: Pre-commit hook

- README.md
- config/default.yml
- lib/overcommit/hook/pre_commit/kt_lint.rb
- spec/overcommit/hook/pre_commit/kt_lint_spec.rb
* Add KtLint pre-commit hook
* Update README
> KtLint: Pre-commit hook

- lib/overcommit/hook/shared/rake_target.rb
- spec/overcommit/hook/pre_commit/chamber_verification_spec.rb
- spec/overcommit/hook/pre_commit/jscs_spec.rb
> Fix misspellings

- spec/overcommit/hook/base_spec.rb
Context
=
Add test before updating the method in other PR (https://github.com/sds/overcommit/pull/681).
> Add Test on Hook Base "run?" Method

- .travis.yml
- overcommit.gemspec
rexml is no longer default gem in Ruby 3.0
> Update for Ruby 3.0

- lib/overcommit/hook/pre_commit/bundle_check.rb
Allow overriding the Gemfile.lock file (respect BUNDLE_GEMFILE env var).
> Allow overriding Gemfile.lock

- config/default.yml
- lib/overcommit/hook/pre_push/mix_test.rb
- spec/overcommit/hook/pre_push/mix_test_spec.rb
A `PrePush` hook to run the test suite in Elixir projects.
> Add `MixTest` hook

- overcommit.gemspec
I think it only brings improvements: https://github.com/enkessler/childprocess/releases/tag/v5.0.0
> Allow childprocess 5

- .github/workflows/tests.yml
- lib/overcommit/hook/pre_commit/rails_schema_up_to_date.rb
- lib/overcommit/hook_context/helpers/file_modifications.rb
- spec/overcommit/git_repo_spec.rb
- spec/overcommit/hook/prepare_commit_msg/base_spec.rb
- spec/overcommit/hook_context/commit_msg_spec.rb
- spec/overcommit/hook_context/post_checkout_spec.rb
- spec/overcommit/hook_context/post_commit_spec.rb
- spec/overcommit/hook_context/post_merge_spec.rb
- spec/overcommit/hook_context/post_rewrite_spec.rb
- spec/overcommit/hook_context/pre_commit_spec.rb
- spec/overcommit/hook_context/run_all_spec.rb
- spec/overcommit/installer_spec.rb
This reverts commit 607ce057b760b697dc63623e7b7dc06a79316eab.
Going to try to merge a different branch.
> Revert "Get suite running smoothly again (#824)"
